### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dc932dc** [CLDeveloping/chrome-bookmark#5]

**Comment by cyolc932** [comment]
## [[附加组件开发者中心](https://addons.mozilla.org/zh-CN/developers/)](https://addons.mozilla.org/zh-CN/developers/)：Chrome拓展在Firefox上使用

- 进入[[附加组件开发者中心](https://addons.mozilla.org/zh-CN/developers/)](https://addons.mozilla.org/zh-CN/developers/)

- [[提交新附加组件](https://addons.mozilla.org/zh-CN/developers/addon/submit/agreement)](https://addons.mozilla.org/zh-CN/developers/addon/submit/agreement)

- 选择`由您自己托管。`

- 提交新附加组件：上传版本（把源码打包压缩，查看压缩包内是否有`.json`文件，如果没有就压缩后解压再压缩)

- 最后会问是否`公开提交源代码`(点`否`)

- 等待审核通过即可在个人[[附加组件开发者中心](https://addons.mozilla.org/zh-CN/developers/)](https://addons.mozilla.org/zh-CN/developers/)查看上传的内容
